import type { Metadata } from "next";
import "./globals.css";
import { Navigation } from "@/components/navigation";
import { auth, signIn } from "@/auth";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  if (!session) {
    return (
      <html lang="en">
        <body
          className={`antialiased`}
        >
          <form
            action={async () => {
              "use server";
              await signIn();
            }}
          >
            <button type="submit">Sign in</button>
          </form>
        </body>
      </html>
    );
  }
  return (
    <html lang="en" className="w-screen h-screen">
      <body
        className={`antialiased w-screen h-screen`}
      >
        <Navigation username={session.user?.name}>{children}</Navigation>
      </body>
    </html>
  );
}
